all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site01:
      children:
        archlinux:
          children:
            arch:
              hosts:
                192.168.30.64:
            archarm:
              hosts:
                192.168.30.3:
                192.168.30.10:
                192.168.30.11:
                192.168.30.20:
                192.168.30.61:

        lxc:
          hosts:
            192.168.30.3:
            192.168.30.10:
            192.168.30.11:
            192.168.30.20:
            192.168.30.61:
            192.168.30.64:

        kubernetes:
          children:
            kubernetes_proxy:
            kubernetes_worker:
            kubernetes_master:

        worker:
          hosts:
            192.168.30.64:

        bastion:
          hosts:
            192.168.30.10:
            192.168.30.11:

        dns:
          hosts:
            192.168.30.3:

        redmine:
          children:
            mariadb:
              hosts:
                192.168.30.20:

        cache:
          children:
            pacman:
              children:
                arm:
                  hosts:
                    192.168.30.61:

