all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site01:
      children:
        archlinux:
          children:
            arch:
              hosts:
            archarm:
              hosts:
                192.168.30.20:
                192.168.30.21:

        lxc:
          hosts:

        kubernetes:
          children:
            kubernetes_proxy:
            kubernetes_worker:
            kubernetes_master:

        bastion:
          hosts:

        docker:
          hosts:

        grafana:
          hosts:
            192.168.30.20:

        jenkins:
          hosts:
            192.168.30.21:

        dns:
          hosts:

        proxmox:
          hosts:
            192.168.30.55:

