all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site02:
      children:
        archlinux:
          children:
            arch:
              hosts:
                192.168.32.100:
                192.168.32.60:
            archarm:
              hosts:
                192.168.32.30:
                192.168.32.31:

        lxc:
          hosts:
            192.168.32.100:
            192.168.32.60:

        kubernetes:
          children:
            kubernetes_proxy:
            kubernetes_worker:
            kubernetes_master:

        bastion:
          hosts:
            192.168.32.60:

        docker:
          hosts:

        grafana:
          hosts:
            192.168.32.30:

        jenkins:
          hosts:
            192.168.32.31:

        dns:
          hosts:
            192.168.32.100:

        proxmox:
          hosts:
            192.168.32.50:

