all:
  hosts:
  vars:
    ansible_user: maintainer

    children:
      site02:
        children:
          archlinux:
            children:
              arch:
                hosts:
                  192.168.17.20:
                  192.168.17.30:
              archarm:
                hosts:

          lxc:
            hosts:

          kubernetes:
            children:
              kubernetes_proxy:
              kubernetes_worker:
              kubernetes_master:

          bastion:
            hosts:
              192.168.17.20:

          docker:
            hosts:
              192.168.17.30:

