all:
  hosts:
  vars:
    ansible_user: maintainer

  children:
    site02:
      children:
        archlinux:
          children:
            arch:
              hosts:
            archarm:
              hosts:
                192.168.32.30:
                192.168.32.31:

        lxc:
          hosts:

        kubernetes:
          children:
            kubernetes_proxy:
            kubernetes_worker:
            kubernetes_master:

        bastion:
          hosts:

        docker:
          hosts:

