---
monitoring_packages:
  - name: prometheus
  - name: prometheus-node-exporter

kubernetes_packages:
  - name: containerd
  - name: crictl
  - name: kubeadm
  - name: kubelet
  - name: kubectl
  - name: cni-plugins
  - name: socat
  - name: ethtool
  - name: iptables-nft
  - name: conntrack-tools
  - name: argocd

kubernetes_master_packages:
  - name: helm
  - name: kustomize

kubernetes_proxy_packages:
  - name: nginx

servers:
  - name: kube-proxy01
    address: "192.168.30.36"
  - name: kube-cp01
    address: "192.168.30.30"
  - name: kube-cp02
    address: "192.168.30.34"
  - name: kube-cp03
    address: "192.168.30.35"
  - name: kube-nd01
    address: "192.168.30.31"
  - name: kube-nd02
    address: "192.168.30.32"
  - name: kube-nd03
    address: "192.168.30.33"

master_servers:
  - name: kube-cp01
    address: "192.168.30.30"
  - name: kube-cp02
    address: "192.168.30.34"
  - name: kube-cp03
    address: "192.168.30.35"

proxy_servers:
  - name: kube-proxy01
    address: "192.168.30.36"
