---
records:
  - name: grafana
    address: "192.168.30.10"
  - name: gitlab
    address: "192.168.30.20"
  - name: proxmox
    address: "192.168.30.5"
  - name: argocd
    address: "192.168.30.181"
  - name: nas
    address: "192.168.11.5"
