---
base_packages:
  - name: sudo
  - name: zsh
  - name: zsh-completions
  - name: vim
  - name: mosh
  - name: git
  - name: base-devel
  - name: rustup
  - name: python-pip
  - name: python-setuptools

authorized_keys:
  - key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH1+DvxUVbKQVrRsRhZEX/aqdox/MU3nC9bqmJBDz+by homelab
  - key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMz2Z8uOw2WCkEQgaQtpDxCNqAPsRFiVCiXQrSzzo+vb
  - key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKZJc89W8z5FzkZpbA4Hl6RXyX5t8nlWingBKMlFPAaw JuiceSSH
  - key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICjNJdBqWLhyP2Q+RznyhSCzf0UPeHUVNaKJEq5QjNE1 GPDWM
  - key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHFKnlIyCgW31Fah9Lu/f0Sn2SYvSN69VkoBqJBSOSV0 maintainer@ansible01
