---
# stormsshの依存関係
- name: 'paramikoをインストール'
  become: true
  community.general.pacman:
    name: python-paramiko
    state: latest

# community.general.ssh_config の依存関係
- name: 'stormsshを追加する'
  ansible.builtin.pip:
    name: stormssh
    virtualenv: "~/.bastion/ansible/venv"
    virtualenv_command: "/usr/bin/python -m venv"

- name: '~/.ssh/configを削除する'
  ansible.builtin.file:
    path: '/home/{{ ansible_user }}/.ssh/config'
    state: absent

- name: '~/.ssh/configを作成する'
  community.general.ssh_config:
    user: 'maintainer'
    host: '{{ item.name }}'
    hostname: '{{ item.address }}'
    forward_agent: true
    strict_host_key_checking: 'no'
    state: present
  with_items: '{{ servers }}'

- name: '~/.ssh/configにgithub用の情報を追加'
  community.general.ssh_config:
    user: 'maintainer'
    remote_user: 'git'
    host: 'github.com'
    hostname: 'github.com'
    state: present
