---
- name: 'grafanaをインストール'
  become: true
  community.general.pacman:
    name: grafana
    state: latest

- name: 'grafana.serviceを有効化'
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: grafana

- name: 'prometheusをインストール'
  become: true
  community.general.pacman:
    name: prometheus
    state: latest

- name: 'prometheusの設定を置く'
  become: true
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: 'prometheus.serviceを有効化'
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: prometheus

