---
- name: 'grafanaをインストール'
  become: true
  community.general.pacman:
    name: grafana
    state: latest

# TODO: /etc/grafana.ini を編集して配置する

- name: 'grafana.serviceを有効化'
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: grafana
