---
- name: 'grafanaをインストール'
  kewlfft.aur.aur:
    name:
      - grafana-bin
    state: present

- name: 'grafana.serviceを有効化'
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: grafana

- name: 'prometheusをインストール'
  become: true
  community.general.pacman:
    name: prometheus
    state: latest

- name: 'prometheusの設定を置く'
  become: true
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  register: prometheus

- name: 'prometheusを有効化'
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: prometheus

- name: 'prometheusを再読み込み'
  become: true
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: prometheus
  when: prometheus.changed == true


