---
- name: 'masterに必要なパッケージを追加する'
  become: true
  community.general.pacman:
    name: '{{ item.name }}'
    state: installed
  with_items: '{{ kubernetes_master_packages  }}'
  when: "'kubernetes-master' in group_names"

- name: 'masterに必要なaurパッケージを追加する'
  become: true
  kewlfft.aur.aur:
    name: '{{ item.name }}'
    state: present
  with_items: '{{ kubernetes_aur_packages }}'
  when: "'kubernetes-master' in group_names"

- name: 'workerに必要なパッケージを追加する'
  become: true
  community.general.pacman:
    name: '{{ item.name }}'
    state: installed
  with_items: '{{ kubernetes_worker_packages  }}'
  when: "'kubernetes-worker' in group_names"

- name: 'proxyに必要なパッケージを追加する'
  become: true
  community.general.pacman:
    name: nginx
    state: installed
  when: "'kubernetes-proxy' in group_names"

- name: '/etc/hostsを置く'
  become: true
  ansible.builtin.template:
    src: etc-hosts.j2
    dest: /etc/hosts
  vars:
    item: '{{ servers }}'

- name: 'nginx.confを置く'
  become: true
  ansible.builtin.template:
    src: nginx-conf.j2
    dest: /etc/nginx/nginx.conf
  vars:
    item: '{{ master_servers }}'
  when: "'kubernetes-proxy' in group_names"

- name: 'kubelet.serviceを有効化'
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: kubelet
  when: "not 'kubernetes-proxy' in group_names"
