---
- name: 'dnsmasqをインストール'
  become: true
  community.general.pacman:
    name: dnsmasq
    state: latest

- name: 'dnsmasqの設定を置く'
  become: true
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf

- name: 'ローカルDNSのレコード設定を置く'
  become: true
  ansible.builtin.template:
    src: hosts-dnsmasq.j2
    dest: /etc/hosts-dnsmasq
  vars:
    item: '{{ records }}'

- name: 'dnsmasq.serviceを有効化'
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: dnsmasq
