- name: 'tailscaleをインストール'
  become: true
  community.general.pacman:
    name: tailscale
    state: latest

- name: 'sysctlの設定を置く'
  become: true
  ansible.builtin.copy:
    src: 99-tailscale.conf
    dest: /etc/sysctl.d/99-tailscale.conf

- name: 'tailscaled.serviceを有効化'
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: tailscaled

