- name: 'dockerをインストール'
  become: true
  community.general.pacman:
    name: 
      - docker
      - docker-compose
      - docker-buildx
    state: latest

- name: 'docker.serviceを有効化'
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: docker

- name: 'dockerグループを作成する'
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: 'コンテナ管理用のユーザを作成する'
  become: true
  ansible.builtin.user:
    name: runner
    shell: /usr/bin/zsh
    groups: docker, wheel
    append: yes
    password: "{{ vault_maintainer_password | password_hash('sha512') }}"

