---
- name: "rsyncを入れる"
  become: true
  community.general.pacman:
    name: rsync
    state: latest

- name: "キャッシュを同期する(x86_64)"
  become: true
  ansible.posix.synchronize:
    mode: pull
    src: rsync://192.168.30.61/x86_64/
    dest: /var/cache/pacman/pkg/
  delegate_to: "{{ inventory_hostname }}"
  when: "'arch' in group_names"

- name: "キャッシュを同期する(aarch64)"
  become: true
  ansible.posix.synchronize:
    mode: pull
    src: rsync://192.168.30.61/aarch64/
    dest: /var/cache/pacman/pkg/
  delegate_to: "{{ inventory_hostname }}"
  when: "'archarm' in group_names"

- name: "archlinux-keyringを先に更新かける"
  become: true
  community.general.pacman:
    name: archlinux-keyring
    state: latest
    update_cache: yes

- name: "pacman -Syyuする"
  become: true
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  register: result

- name: "更新されたパッケージがあるなら、再起動"
  become: true
  ansible.builtin.reboot:
    msg: "Ansibleでパッケージ更新があったので、再起動します"
  when: result.changed == true and "not 'deployer' in group_names"

