---
- name: "archlinux-keyringを先に更新かける"
  become: true
  community.general.pacman:
    name: archlinux-keyring
    state: latest
    update_cache: yes

- name: "pacman -Syyuする"
  become: true
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  register: result

- name: "更新されたパッケージがあるなら、再起動"
  become: true
  ansible.builtin.reboot:
    msg: "Ansibleでパッケージ更新があったので、再起動します"
  when: result.changed == true and "not 'deployer' in group_names"
